# Species migration portfolio assignment : Part 6

In this assignment I use data from the [GBIF]() on the barn swallow migration 

Public Domain, [Media Info](https://www.usgs.gov/media/images/costumed-care-taker-training-whooping-crane-chick)



Growing up in Madison, Wisconsin we would see many seasonal bird migrations. The 1996 family movie [Fly Away Home]( https://en.wikipedia.org/w/index.php?title=Fly_Away_Home&oldid=1380502632) tells the story of a Dad and daughter who rescue orphaned geese and build an ultralight plane to teach them to migrate. This movie was my personal introduction to bird migration and restoration techniques. In Madison migrating geese were a common sight, but we sometimes saw cranes! In the fall my family would go to a nearby state park to walk their boardwalk trails and look for cranes. We were always on the lookout for endangered whooping cranes. I learned from a young age about the incredible efforts to reintroduce Whooping cranes, and their traditional migratory path, to the Midwest. Whooping cranes typically migrate from upper Midwest in summer down to the Southeast in the winter (Thompson et al., 2022). This migration was fully halted due to habitat loss and near-fatal population collapse in the 1940s when the population was reduced to 21 individuals across two fragment populations (Urbanek et al., 2010). In the 1960s dedicated and creative reintroduction efforts began using costumed caretakers and ultralight aircraft to socialize captive-breed cranes and teach the traditional migration path. These, along with other efforts, have brought the population to 76 individuals in 2021, 16 of which were born in the wild (Thompson et al., 2022).

The USGS notes that while whooping cranes are still endangered their population has grown more than tenfold in the last 50 years, thanks to captive breeding and reintroduction efforts. (USDA Site,https://www.usgs.gov/news/featured-story/significant-milestone-whooping-crane-recovery)

## Set up

In [8]:
### Bring in stored var 

##These from 05 notebook
%store -r ecoreg_gdf portfolio_gbif_gdf portfolio_gbif_path gbif_dir ecoreg_gdf

##These from the repo-wide setup-filepaths.ipynb
%store -r portfolio_dir assignments_dir img_dir posts_dir

In [3]:
### import packages

### libraries for dynamic mapping

### manage coordinate ref systems
import cartopy.crs as ccrs

### customize dynamic plot
import panel as pn

### make dynamic plot with geodataframe
import hvplot.pandas
import holoviews as hv

### Run this fix if the plot is not showing, once per kernal session
hvplot.extension("bokeh")

### get month names
import calendar

### folder/file management
import os
import pathlib

### tabular data
import pandas as pd

### geospatial vactor data
import geopandas as gpd
import earthpy as et

## Step 2: Load (GBIF) geodataframe

## Step 3: Connect the GBIF observations to the ecoregions

### Step 3A: Identify the ecoregion for each observation

Here I combine the ecoregions and the observations using a spatial join.

In [3]:
### join the gbif observations to the ecoregion polygons
portfolio_gbif_ecoregion_gdf = (
    ecoreg_gdf
    
    ### match the CRS of the gbif data and the ecoregions
    .to_crs(portfolio_gbif_gdf.crs)

    ### find ecoregion for each observation
    .sjoin(
        portfolio_gbif_gdf,
        ### type of database join
        how = 'inner', 
        ###
        predicate = 'contains')

    ### any additional manipulations you want to do )
    .rename(columns = {'OBJECTID': 'ecoregion'})
)
### check it out
portfolio_gbif_ecoregion_gdf

,ecoregion,ECO_NAME,BIOME_NUM,BIOME_NAME,REALM,ECO_BIOME_,NNH,ECO_ID,SHAPE_LENG,SHAPE_AREA,NNH_NAME,COLOR,COLOR_BIO,COLOR_NNH,LICENSE,geometry,gbifID,month
32,33.0,Appalachian-Blue Ridge forests,4.0,Temperate Broadleaf & Mixed Forests,Nearctic,NE04,2,331,66.560538,16.637804,Nature Could Reach Half Protected,#00734C,#00734C,#7BC141,CC-BY 4.0,"MULTIPOLYGON (((-81.24044 35.86166, -81.24448 ...",5935306074,12
32,33.0,Appalachian-Blue Ridge forests,4.0,Temperate Broadleaf & Mixed Forests,Nearctic,NE04,2,331,66.560538,16.637804,Nature Could Reach Half Protected,#00734C,#00734C,#7BC141,CC-BY 4.0,"MULTIPOLYGON (((-81.24044 35.86166, -81.24448 ...",5279780039,1
93,95.0,Canadian Aspen forests and parklands,8.0,"Temperate Grasslands, Savannas & Shrublands",Nearctic,NE08,4,386,86.836978,40.677412,Nature Imperiled,#DB931A,#FEFF73,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-110.18389 49.92729, -110.1398...",5154852238,5
93,95.0,Canadian Aspen forests and parklands,8.0,"Temperate Grasslands, Savannas & Shrublands",Nearctic,NE08,4,386,86.836978,40.677412,Nature Imperiled,#DB931A,#FEFF73,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-110.18389 49.92729, -110.1398...",5840149332,10
93,95.0,Canadian Aspen forests and parklands,8.0,"Temperate Grasslands, Savannas & Shrublands",Nearctic,NE08,4,386,86.836978,40.677412,Nature Imperiled,#DB931A,#FEFF73,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-110.18389 49.92729, -110.1398...",6400409431,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,789.0,Western Gulf coastal grasslands,7.0,"Tropical & Subtropical Grasslands, Savannas & ...",Nearctic,NE07,4,384,71.700276,8.340400,Nature Imperiled,#FBFC58,#FEAA01,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-97.19822 26.06972, -97.1974 2...",5897307799,11
783,789.0,Western Gulf coastal grasslands,7.0,"Tropical & Subtropical Grasslands, Savannas & ...",Nearctic,NE07,4,384,71.700276,8.340400,Nature Imperiled,#FBFC58,#FEAA01,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-97.19822 26.06972, -97.1974 2...",5063760810,1
783,789.0,Western Gulf coastal grasslands,7.0,"Tropical & Subtropical Grasslands, Savannas & ...",Nearctic,NE07,4,384,71.700276,8.340400,Nature Imperiled,#FBFC58,#FEAA01,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-97.19822 26.06972, -97.1974 2...",5070106538,2
783,789.0,Western Gulf coastal grasslands,7.0,"Tropical & Subtropical Grasslands, Savannas & ...",Nearctic,NE07,4,384,71.700276,8.340400,Nature Imperiled,#FBFC58,#FEAA01,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-97.19822 26.06972, -97.1974 2...",5932479880,12
783,789.0,Western Gulf coastal grasslands,7.0,"Tropical & Subtropical Grasslands, Savannas & ...",Nearctic,NE07,4,384,71.700276,8.340400,Nature Imperiled,#FBFC58,#FEAA01,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((-97.19822 26.06972, -97.1974 2...",5063772417,1

### Step 3B: Count the observations in each ecoregion each month

First, group the GBIF observations by ecoregion:
1. Count the observations in each ecoregion by month.
2. Select only month/ecoregion combinations that have more than one occurrence recorded
3. Compute the mean occurrences by ecoregion and by month.
4. Normalize the number of occurrences by month and ecoregion.

In [4]:
### summarize the occurrences by ecoregion/month combination
portfolio_occurrence_df = (
    portfolio_gbif_ecoregion_gdf

    ### group by each ecoregion and month 
    .groupby(['ecoregion', 'month'])

    ### and count the number of occurrences
    .agg(occurrences=('ecoregion', 'count'))
)
portfolio_occurrence_df.head()

### get rid of rare observations (which are possibly misidentifications)
portfolio_occurrence_df = portfolio_occurrence_df[portfolio_occurrence_df.occurrences > 1]

### calculate the mean # observations by ecoregion
portfolio_mean_occurrences_by_ecoregion = (
    portfolio_occurrence_df
    .groupby('ecoregion')
    .mean()
)

### calculate the mean # observations by month
portfolio_mean_occurrences_by_month = (
    portfolio_occurrence_df
    .groupby('month')
    .mean()
)

portfolio_mean_occurrences_by_ecoregion, portfolio_mean_occurrences_by_month

(           occurrences
 ecoregion
 95.0         21.000000
 126.0         8.500000
 140.0         3.666667
 191.0         2.000000
 215.0         2.000000
 338.0        11.666667
 518.0         2.000000
 666.0         5.250000
 764.0         7.857143
 789.0        22.666667,
        occurrences
 month
 1        19.000000
 2        19.500000
 3        13.333333
 4         2.750000
 5        13.000000
 6         5.500000
 7         7.500000
 8         5.000000
 9         4.000000
 10       14.000000
 11        8.400000
 12       15.000000)

### Step 3C: Normalize the observations

Divide occurrences by the mean occurrences by month and by ecoregion.

In [ ]:
### normalize by space and time for sampling effort
portfolio_occurrence_df['norm_occurrences'] = (
    portfolio_occurrence_df
    / portfolio_mean_occurrences_by_ecoregion
    / portfolio_mean_occurrences_by_month
)

### check it out
portfolio_occurrence_df

                 occurrences  norm_occurrences
ecoregion month
95.0      9                5          0.059524
          10              37          0.125850
126.0     3                8          0.070588
          11               9          0.126050
140.0     4                2          0.198347
          5                5          0.104895
          6                4          0.198347
          7                7          0.254545
          9                2          0.136364
          11               2          0.064935
191.0     11               2          0.119048
215.0     9                2          0.250000
338.0     1               11          0.049624
          11              10          0.102041
          12              14          0.080000
518.0     4                2          0.363636
666.0     1               12          0.120301
          2                5          0.048840
          3                2          0.028571
          10               2          0.027211
764.0     4                4          0.185124
          5               21          0.205594
          6                7          0.161983
          7                8          0.135758
          8                5          0.127273
          9                7          0.222727
          10               3          0.027273
789.0     1               34          0.078947
          2               34          0.076923
          3               30          0.099265
          4                3          0.048128
          11              19          0.099790
          12              16          0.047059

:

In [ ]:
### histogram
portfolio_occurrence_df.norm_occurrences.plot.hist()

### scatterplot
portfolio_occurrence_df.reset_index().plot.scatter(
    x = 'month', 
    y = 'norm_occurrences',
    c= 'ecoregion')

## Step 5: Make an interactive map of GBIF observations

### Step 5A: Create a simplified `GeoDataFrame` for plotting

Plotting larger files can be time consuming. The code below will streamline plotting with `hvplot` by simplifying the geometry, projecting it to a Mercator projection that is compatible with `geoviews`, and cropping off areas in the Arctic:

1. Simplify the ecoregions with `.simplify(.05)`, and save it back to the `geometry` column.
2. Change the Coordinate Reference System (CRS) to Mercator with `.to_crs(ccrs.Mercator())`.
3. Use the plotting code that is already in the cell to check that the plotting runs quickly (less than a minute) and looks the way you want, making sure to change `gdf` to your `GeoDataFrame` name.

In [ ]:
### simplify the geometry to speed up processing
ecoreg_gdf.geometry = ecoreg_gdf.geometry.simplify(
    0.05, preserve_topology=False)

### change the CRS to Mercator for mapping
ecoreg_gdf = ecoreg_gdf.to_crs(ccrs.Mercator())

### check that the plot runs in a reasonable amount of time
hvplot.extension("bokeh")

ecoreg_gdf.hvplot(geo = True, crs = ccrs.Mercator())

:Polygons   [Longitude,Latitude]

In [ ]:
ecoreg_gdf.head()

,OBJECTID,ECO_NAME,BIOME_NUM,BIOME_NAME,REALM,ECO_BIOME_,NNH,ECO_ID,SHAPE_LENG,SHAPE_AREA,NNH_NAME,COLOR,COLOR_BIO,COLOR_NNH,LICENSE,geometry
0,1.0,Adelie Land tundra,11.0,Tundra,Antarctica,AN11,1,117,9.749780,0.038948,Half Protected,#63CFAB,#9ED7C2,#257339,CC-BY 4.0,"POLYGON ((17090104.083 -10646152.188, 17100906..."
1,2.0,Admiralty Islands lowland rain forests,1.0,Tropical & Subtropical Moist Broadleaf Forests,Australasia,AU01,2,135,4.800349,0.170599,Nature Could Reach Half Protected,#70A800,#38A700,#7BC141,CC-BY 4.0,"MULTIPOLYGON (((16461836.873 -254248.259, 1644..."
2,3.0,Aegean and Western Turkey sclerophyllous and m...,12.0,"Mediterranean Forests, Woodlands & Scrub",Palearctic,PA12,4,785,162.523044,13.844952,Nature Imperiled,#FF7F7C,#FE0000,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((3391149.749 4336064.109, 33985..."
3,4.0,Afghan Mountains semi-desert,13.0,Deserts & Xeric Shrublands,Palearctic,PA13,4,807,15.084037,1.355536,Nature Imperiled,#FA774D,#CC6767,#EE1E23,CC-BY 4.0,"MULTIPOLYGON (((7369001.698 4093509.259, 73168..."
4,5.0,Ahklun and Kilbuck Upland Tundra,11.0,Tundra,Nearctic,NE11,1,404,22.590087,8.196573,Half Protected,#4C82B6,#9ED7C2,#257339,CC-BY 4.0,"MULTIPOLYGON (((-17912546.29 8050475.591, -179..."

In [ ]:
### prep the data, then combine the occurrence data with the ecoregions

### rename columns in ecoregID to match occurrence_df
ecoreg_gdf = ecoreg_gdf.rename(columns = {'OBJECTID': 'ecoregion'})

### make ecoreg ID the index for merge with occurrence_df
### Run this once but comment out if you rerun
ecoreg_gdf = ecoreg_gdf.set_index('ecoregion')

### join the occurrences with the plotting GeoDataFrame
portfolio_occurrence_gdf = ecoreg_gdf.join(portfolio_occurrence_df)

portfolio_occurrence_gdf

In [ ]:
### plot the data

### get the plot bounds so they don't change with the slider
xmin, ymin, xmax, ymax = portfolio_occurrence_gdf.total_bounds

### define the slider widget
slider = pn.widgets.DiscreteSlider(
    name = 'month', 
    options = {calendar.month_name[i]: i for i in range(1, 13)}
)

### plot occurrence by ecoregion and month
migration_plot = (
    portfolio_occurrence_gdf
    .hvplot(
        ### Color by number veeries
        c = 'norm_occurrences',
        groupby = 'month',

        ### use background tiles
        geo = True, crs = ccrs.Mercator(), tiles = 'OSM',

        ### add a title
        title = "Yearly Veery Migration",

        ### set plot boundaries
        xlim = (xmin, xmax), ylim = (ymin, ymax),

        ### set dimensions of map
        frame_height = 600,
        frame_width = 900,

        ### put the widget at the bottom of the map
        widget_location = 'bottom',
        colorbar = False, ## True will categorize the colorbar but then the scale changes with slide
        widgets = {'month': slider}
    )
)

### wrap  plot in the Panel layout
interactive_migration_plot = pn.panel(migration_plot)

### check it out
interactive_migration_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'eaf9b008-c4fe-49b9-8b97-d51db102ad42': {'version…

In [ ]:
### make a version for export, without the basemap
export_portfolio_plot = (
    portfolio_occurrence_gdf
    .hvplot(
        ### Color by number veeries
        c = 'norm_occurrences',
        groupby = 'month',

        ### add a title
        title = "Yearly Whooping Crane Migration",
        xlabel = "Longitude", ylabel = "Latitude",

        ### set plot boundaries
        xlim = (xmin, xmax), ylim = (ymin, ymax),

        ### set dimensions of map
        frame_height = 600,
        frame_width = 900,

        ### put the widget at the bottom of the map
        widget_location = 'bottom',
        colorbar = False,
        widgets = {'month': slider}
    )
)
export_portfolio_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'35c9b6b9-221f-4a91-ab96-71ea33599d9f': {'version…

### Basemap demo

In [ ]:
hvplot.extension("bokeh")
### get the plot bounds so they don't change with the slider
xmin, ymin, xmax, ymax = portfolio_occurrence_gdf.total_bounds

### define the slider widget
slider = pn.widgets.DiscreteSlider(
    name = 'month', 
    options = {calendar.month_name[i]: i for i in range(1, 13)}
)

## make basemap title object
carto_tiles = hv.Tiles(
    ("https://basemaps.cartocdn.com/rastertiles/voyager/{Z}/{X}/{Y}.png"
    "?key=cb1_446c_1_8946b413de0ace50f732dbf1"),
    name = "CARTO"
)

### make a version for export, without the basemap
basemap_portfolio_plot = (
    portfolio_occurrence_gdf
    .hvplot(
        ### Color by number veeries
        c = 'norm_occurrences',
        cmap = 'viridis',
        groupby = 'month',
        geo = True, 
        crs = ccrs.Mercator(), 
        tiles = carto_tiles,

        ### add a title
        title = "Yearly Whooping Crane Migration",
        xlabel = "Longitude", ylabel = "Latitude",

        ### set plot boundaries
        xlim = (xmin, xmax), ylim = (ymin, ymax),

        ### set dimensions of map
        frame_height = 600,
        frame_width = 900,

        ### put the widget at the bottom of the map
        widget_location = 'bottom',
        colorbar = False,
        widgets = {'month': slider}
    )
)
basemap_portfolio_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'a25d5eda-83d7-4913-ad04-b1e2380994d6': {'version…

## Export Plot as html for portfolio

In [9]:
### Make a home for the map

### create data directory
portfolio_map_path = os.path.join(img_dir, 'post_migration_crane_map.html')
portfolio_map_path

'C:\\Users\\nyca4176\\Repos\\earth-data-portfolio\\img\\post_migration_crane_map.html'

In [ ]:
## export map
basemap_portfolio_plot.save(
    portfolio_map_path, 
    embed = True,
    resources = 'inline'
)